PREFIX me: <http://example.org/>
PREFIX class: <http://example.org/class/>
PREFIX property: <http://example.org/property/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rel: <http://www.perceive.net/schemas/relationship/>

SELECT ?travel ?traveler ?name ?date ?wifi ?fontaine
WHERE {
  ?travel rdf:type class:Travel .
  ?travel property:date "#DATE" .
  ?travel property:date ?date .
  ?travel property:traveler ?traveler .
  ?traveler property:name ?name .
  OPTIONAL {
  ?travel property:wifi ?wifi .}
  OPTIONAL {
  ?travel property:fontaine ?fontaine .}
}
ORDER BY ?travel

